const DESCRIPTIONS: Readonly<Record<string, string>> = {
  proxy_history: "Get Burp proxy history with optional filtering by URL, method, status code",
  proxy_detail: "Get full request/response details for a specific proxy history item by index",
  proxy_websocket: "Get WebSocket message history",
  proxy_clear: "Clear proxy history",
  proxy_history_filtered: "Filter proxy history by annotation color or notes",
  send_request: "Send an HTTP request through Burp and get the response",
  send_to_repeater:
    "Display a raw HTTP request in Burp Repeater without sending it. tab_name is an optional tab caption, not a tag.",
  repeater_send: "Send a request and get response (like Repeater)",
  repeater_modify_send: "Modify headers/body of a request then send it",
  send_to_intruder: "Send a request to Burp Intruder",
  intruder_attack: "Run a numeric range brute force attack (synchronous)",
  intruder_attack_async: "Run a multi-threaded numeric range brute force attack",
  intruder_attack_wordlist: "Run a wordlist-based attack",
  intruder_pitchfork: "Run a Pitchfork attack (parallel multi-param)",
  intruder_cluster_bomb: "Run a Cluster Bomb attack (cartesian product multi-param)",
  intruder_battering_ram: "Run a Battering Ram attack (same payload all positions)",
  intruder_with_options: "Run attack with advanced options (throttle, encoding, grep, timing)",
  sitemap: "Get site map entries with optional URL prefix filter",
  target_info: "Get target information (hosts, technologies detected)",
  intercept_toggle: "Enable or disable proxy intercept",
  encode: "Encode a string (base64, url, hex)",
  decode: "Decode a string (base64, url)",
  convert_request: "Convert HTTP request method (e.g. GET to POST)",
  export_request: "Export a request as curl or Python requests code",
  generate_csrf_poc: "Generate a CSRF proof-of-concept HTML page",
  extract_from_response: "Extract data from a response using regex",
  payload_process: "Process a payload (hash, encode, reverse, etc.)",
  scan: "Start a vulnerability scan",
  scan_active:
    "Start a standard legacy active audit for a request. This cannot target or prove execution of a particular BCheck; poll scan_results for discovered issues. Requires Burp Professional.",
  scan_results: "Get scan results (discovered vulnerabilities)",
  scan_issue_detail: "Get detailed information about a specific scan issue",
  crawl: "Start crawling a URL (adds to scope)",
  get_scope: "Check if a URL is in Burp scope",
  add_to_scope: "Add a URL to Burp scope",
  remove_from_scope: "Remove a URL from Burp scope",
  collaborator_generate: "Generate Burp Collaborator payloads for OOB testing",
  collaborator_poll: "Poll for Collaborator interactions (DNS/HTTP callbacks)",
  search_history: "Search proxy history with regex (in URL, request, or response)",
  highlight:
    "Set the highlight color on an item in the current Burp Proxy HTTP history. This does not address Repeater history or tags.",
  annotate:
    "Set notes on an item in the current Burp Proxy HTTP history. This does not address Repeater history or tags.",
  compare: "Compare two proxy history responses (diff)",
  export_config: "Export Burp project configuration as JSON",
  import_config: "Import Burp project configuration from JSON",
  set_upstream_proxy: "Set upstream proxy (SOCKS/HTTP) for all Burp traffic",
  set_dns_override: "Override DNS resolution for a hostname",
  set_http2: "Enable or disable HTTP/2",
  cookie_jar:
    "List cookies in Burp cookie jar with name, value, domain, path, and expiration (optional domain filter)",
  token_analysis: "Analyze token entropy and randomness",
  sequencer: "Analyze a batch of tokens for randomness quality",
  save_project: "Save the current Burp project",
  burp_version: "Get Burp Suite version information",
  add_issue: "Manually add a vulnerability issue to the site map",
  register_http_handler:
    "Register an auto-modify rule for HTTP requests (add header or replace text)",
  remove_http_handler: "Remove/clear HTTP handler rules",
  register_proxy_rule: "Register a proxy intercept rule (intercept URLs containing a string)",
  remove_proxy_rule: "Remove/clear proxy intercept rules",
  extensions_list: "Get information about loaded extensions",
  log: "Write a message to Burp extension output log",
  audit_log: "View audit log entries",
  privacy_mode: "Set privacy mode (strict/off)",
  scope_gate: "Enable/disable scope gate",
  inline_fuzzer: "FUZZ marker fuzzing",
  race_condition: "Race condition testing",
  access_control_sweep: "Test different auth levels",
  injection_probe: "SQLi/SSTI/LFI probe",
  jwt_attack: "JWT attacks (alg:none)",
  jwt_decode: "Decode JWT tokens",
  session_remove_rule: "Remove session rule",
  session_list_rules: "List session rules",
  session_create_rule: "Create session handling rule",
  passive_intel: "Extract secrets from proxy history",
  websocket_list: "List active WebSockets",
  websocket_close: "Close WebSocket",
  websocket_send_binary: "Send binary on WebSocket",
  websocket_send_text: "Send text on WebSocket",
  websocket_create: "Create WebSocket connection",
  send_request_parallel: "Send parallel HTTP requests",
  cookie_jar_set: "Set cookie in Burp cookie jar",
  bambda_import:
    "Import a Bambda script into Burp. Imports only; this tool does not execute the script.",
  bcheck_import:
    "Import a BCheck script into Burp with the requested enabled state. Imports only; this tool does not run the BCheck.",
}

export function getBurpToolDescription(name: string): string {
  return DESCRIPTIONS[name] ?? `Burp Suite tool: ${name}`
}
