[package]
name = "burp-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
burp-protocol = { package = "burp-protocol", path = "../burp-protocol" }
rmcp.workspace = true
schemars.workspace = true
serde.workspace = true
regex.workspace = true
serde_json.workspace = true
sitegraph = { path = "../sitegraph" }
utility-core = { path = "../utility-core" }
utility-tools = { path = "../utility-tools" }
