[package]
name = "sitegraph-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
base64.workspace = true
ciborium.workspace = true
capnp.workspace = true
capnp-rpc.workspace = true
futures.workspace = true
fs2.workspace = true
getrandom.workspace = true
serde.workspace = true
sitegraph = { path = "../sitegraph" }
tokio-util.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true

[[bin]]
name = "sitegraph-daemon"
path = "src/main.rs"

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
capnpc.workspace = true
