[package]
name = "burp-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
interop = []

[dependencies]
prost.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[[test]]
name = "interop"
required-features = ["interop"]

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true
tonic-prost-build.workspace = true

[dev-dependencies]
anyhow.workspace = true
