[package]
name = "utility-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
blake3.workspace = true
brotli.workspace = true
html-escape.workspace = true
flate2.workspace = true
hmac.workspace = true
md-5.workspace = true
percent-encoding.workspace = true
num-bigint = "0.4.6"
regex.workspace = true
sha1.workspace = true
sha2.workspace = true
sha3 = "0.10.8"
serde.workspace = true
serde_json.workspace = true
url.workspace = true
thiserror.workspace = true
